name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
        
    - name: Install NPM packages
      run: npm ci
    
    - name: Run test script
      run: npm run test